site_title = "MyArxiv"
limit_days = 7
cache_url = "https://SylarAnh.github.io/Arxiv/cache.json"

[[sources]]
limit = 150
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
